### ISSUE TITLE
Nats Streaming Client Disconnect Issue

### ISSUE THREAD

**Issue by sachinwalia2k8** [nats-io/go-nats-streaming#159]
I posted this on google groups as well so putting it verbatim:

I am using Golang streaming client and have a following topology:

-- service 1
--- establishes NatsConnection during startup

-- service 2..n
--- establishes NatsConnection during startup
--- sets up Message Handlers once connection is established

What I've noticed from the Nats Streaming Web Console is that after sometimes the list of clients displayed becomes empty. I checked here: http://<nats-host>:8222/streaming/clientsz

Before the client disappears from the Web admin console it displays following message in NATS streaming debug log:

`[25931] 2017/11/05 14:24:05.939637 [DBG] STREAM: [Client:service001] Timed out on heartbeats
`
Consequently what happens is if service 1 sends any message to a topic to which service 2..n are listening via Queue Group then I am getting following error message:
`"stan: invalid publish request"
`
I believe the error is happening because the client is disconnected before it attempts to send message. I am trying to understand why client disconnect is happening. 
Do I need to incorporate some kind of auto reconnect feature?

FYI I am using Nats streaming 0.6 and the latest version of Golang streaming client.

Any help is highly appreciated.

**Comment by kozlovic** [comment]
The error message about heartbeats indicate that the client library is either not heartbeating or that those heartbeats are not reaching the server.

It is unclear from your description if you are creating a NATS connection that you pass to the Streaming `Connect()` call (with `NatsConn()`) or if you create the streaming connection directly.
If the former, make sure that there is not a situation where you would incorrectly close the underlying NATS Connection preventing communication with the Streaming server.

By default, the low level NATS Connection will reconnect (should it get disconnected). You may need to create your own NATS Connection if you want to tweak the reconnect properties.

I would also point to this section in the server README that touches on the use of NATS in NATS Streaming from a client perspective: https://github.com/nats-io/nats-streaming-server#client-connections

**Comment by sachinwalia2k8** [comment]
Hi @kozlovic - I create Nats Streaming Connection directly. Here is the code:

During Microservice startup this block of code gets executed and creates a Global NatsConn instance.

```
	var natsUrl = "nats://"+BootConfig.NatsUser+":"+BootConfig.NatsPassword+"@"+BootConfig.NatsServer+":"+BootConfig.NatsPort
	NatsConn, err = stan.Connect(BootConfig.NatsClusterID, BootConfig.InstanceName, stan.NatsURL(natsUrl))
	if(err != nil){
		Logger.Error("NATS ERROR::Unable to create nats connection", "error", err)
		os.Exit(1)
	}  else {
		Logger.Info("Nats server connection successfully established.")
	}

```

During Microservice shutdown following code gets executed as part of cleanup:

`	NatsConn.Close()
`

**Comment by kozlovic** [comment]
Server is sending heartbeats, clients just echo them. You would have to run the server with `-DV` which adds NATS level debugging/tracing (not NATS Streaming). You should then see something like:
```
[93088] 2017/11/06 10:17:15.404250 [TRC] 127.0.0.1:52395 - cid:2 - ->> [PUB _INBOX.7I1pd65fMZlCGzMWgwBUQi _INBOX.le4uFdw6A4EsoU9ODE9xfc.le4uFdw6A4EsoU9ODE9xoZ 0]
[93088] 2017/11/06 10:17:15.404274 [TRC] 127.0.0.1:52395 - cid:2 - ->> MSG_PAYLOAD: []
[93088] 2017/11/06 10:17:15.404288 [TRC] ::1:52396 - cid:3 - <<- [MSG _INBOX.7I1pd65fMZlCGzMWgwBUQi 1 _INBOX.le4uFdw6A4EsoU9ODE9xfc.le4uFdw6A4EsoU9ODE9xoZ 0]
[93088] 2017/11/06 10:17:15.404752 [TRC] ::1:52396 - cid:3 - ->> [PUB _INBOX.le4uFdw6A4EsoU9ODE9xfc.le4uFdw6A4EsoU9ODE9xoZ 0]
[93088] 2017/11/06 10:17:15.404782 [TRC] ::1:52396 - cid:3 - ->> MSG_PAYLOAD: []
[93088] 2017/11/06 10:17:15.405063 [TRC] 127.0.0.1:52395 - cid:2 - <<- [MSG _INBOX.le4uFdw6A4EsoU9ODE9xfc.le4uFdw6A4EsoU9ODE9xoZ 1 0]
```

**Comment by sachinwalia2k8** [comment]
@kozlovic if server is sending heartbeat to the registered clients then there may be a firewall restriction on mac for an incoming traffic. Do you know which port would server use to send out these heartbeats to clients?

**Comment by kozlovic** [comment]
As you said, the HBs are sent/recv from the same TCP connection than the rest of the data.

**Comment by ColinSullivan1** [comment]
@sachinwalia2k8 , any updates?

**Comment by sachinwalia2k8** [comment]
Hi @ColinSullivan1 , @kozlovic after using an instance of Nats Streaming on the same host as my application I am no longer seeing these errors. It seems to me that OSX by default may be blocking ping to clients due to firewall issues. In my opinion it may be a good idea to mention as potential issue for people running streaming clients on OSX.

**Comment by dagenius007** [comment]
I still get this error and I can't seem to find any solution on the web. @sachin-walia @ColinSullivan1 @kozlovic

**Comment by kozlovic** [comment]
@dagenius007 You have opened an issue in the Node client. What library are you actually using? Also, you say that you get invalid publish when the NATS server is down, which is expected..

**Comment by flipace** [comment]
We also just encountered this issue in production where suddenly nats connections "hung up" - interestingly just before this happened, the nats-streaming-server logged some warnings about readloop processing time:

```
[1] 2020/11/10 19:07:25.917143 [WRN] 172.18.0.1:58036 - cid:77 - Readloop processing time: 12.97811423s
[1] 2020/11/10 19:07:25.917446 [WRN] 172.18.0.1:58026 - cid:76 - Readloop processing time: 13.994519443s
[1] 2020/11/10 19:07:25.917453 [WRN] 172.18.0.1:58076 - cid:78 - Readloop processing time: 14.527211019s
[1] 2020/11/10 19:07:25.917464 [WRN] 172.18.0.1:32768 - cid:70 - Readloop processing time: 10.86900176s
[1] 2020/11/10 19:07:33.654451 [WRN] 127.0.0.1:50300 - cid:1 - Readloop processing time: 6.822063601s
[1] 2020/11/10 19:07:34.516269 [WRN] 172.18.0.1:58076 - cid:78 - Readloop processing time: 3.740781212s
[1] 2020/11/10 19:07:39.038097 [WRN] 127.0.0.1:50300 - cid:1 - Readloop processing time: 5.383617706s
[1] 2020/11/10 19:07:39.038294 [WRN] 127.0.0.1:50302 - cid:2 - Readloop processing time: 12.188599826s
[1] 2020/11/10 19:14:23.650070 [ERR] STREAM: [Client:service-1] Timed out on heartbeats
[1] 2020/11/10 19:14:23.652557 [ERR] STREAM: [Client:service-2] Timed out on heartbeats
[1] 2020/11/10 19:14:23.807304 [ERR] STREAM: [Client:service-3] Timed out on heartbeats
[1] 2020/11/10 19:14:23.807471 [ERR] STREAM: [Client:service-4] Timed out on heartbeats
```

On our service side - the nats connection seems to just have been closed:

```
NatsError: Connection closed
      at Client.publish (/usr/service/node_modules/nats/lib/nats.js:1672:12)
      at Stan.publish (/usr/service/node_modules/node-nats-streaming/lib/stan.js:616:11)
	  ...
```

**Comment by derekcollison** [comment]
The ReadLoop processing time can be stalled like that when a network connection gets wedged and the system starts slowing down trying to send messages to outbound clients. This is a core NATS warning, not NATS Streaming.

Was there a network event? Did the condition clear?
